#ifndef SQUASH_ATTACKING_ANIM_H
#define SQUASH_ATTACKING_ANIM_H

#define SQUASH_ATTACKING_WIDTH  32
#define SQUASH_ATTACKING_HEIGHT 35
#define SQUASH_ATTACKING_FRAMES 3

extern unsigned char squash_attacking_frames[SQUASH_ATTACKING_FRAMES][SQUASH_ATTACKING_WIDTH*SQUASH_ATTACKING_HEIGHT];

#endif
