#ifndef BALLOON_ZOMBIE_FIGHT_ANIM_H
#define BALLOON_ZOMBIE_FIGHT_ANIM_H

#define BALLOON_ZOMBIE_FIGHT_WIDTH  36
#define BALLOON_ZOMBIE_FIGHT_HEIGHT 46
#define BALLOON_ZOMBIE_FIGHT_FRAMES 4

extern unsigned char balloon_zombie_fight_frames[BALLOON_ZOMBIE_FIGHT_FRAMES][BALLOON_ZOMBIE_FIGHT_WIDTH*BALLOON_ZOMBIE_FIGHT_HEIGHT];

#endif
