#ifndef BALLOON_ZOMBIE_FLY_ANIM_H
#define BALLOON_ZOMBIE_FLY_ANIM_H

#define BALLOON_ZOMBIE_FLY_WIDTH  35
#define BALLOON_ZOMBIE_FLY_HEIGHT 53
#define BALLOON_ZOMBIE_FLY_FRAMES 20

extern unsigned char balloon_zombie_fly_frames[BALLOON_ZOMBIE_FLY_FRAMES][BALLOON_ZOMBIE_FLY_WIDTH*BALLOON_ZOMBIE_FLY_HEIGHT];

#endif
