#ifndef BALLOON_ZOMBIE_DEATH_ANIM_H
#define BALLOON_ZOMBIE_DEATH_ANIM_H

#define BALLOON_ZOMBIE_DEATH_WIDTH  40
#define BALLOON_ZOMBIE_DEATH_HEIGHT 29
#define BALLOON_ZOMBIE_DEATH_FRAMES 15

extern unsigned char balloon_zombie_death_frames[BALLOON_ZOMBIE_DEATH_FRAMES][BALLOON_ZOMBIE_DEATH_WIDTH*BALLOON_ZOMBIE_DEATH_HEIGHT];

#endif
