#ifndef BALLOON_ZOMBIE_POP_ANIM_H
#define BALLOON_ZOMBIE_POP_ANIM_H

#define BALLOON_ZOMBIE_POP_WIDTH  36
#define BALLOON_ZOMBIE_POP_HEIGHT 58
#define BALLOON_ZOMBIE_POP_FRAMES 12

extern unsigned char balloon_zombie_pop_frames[BALLOON_ZOMBIE_POP_FRAMES][BALLOON_ZOMBIE_POP_WIDTH*BALLOON_ZOMBIE_POP_HEIGHT];

#endif
