#ifndef BALLOON_ZOMBIE_WALK_ANIM_H
#define BALLOON_ZOMBIE_WALK_ANIM_H

#define BALLOON_ZOMBIE_WALK_WIDTH  35
#define BALLOON_ZOMBIE_WALK_HEIGHT 44
#define BALLOON_ZOMBIE_WALK_FRAMES 16

extern unsigned char balloon_zombie_walk_frames[BALLOON_ZOMBIE_WALK_FRAMES][BALLOON_ZOMBIE_WALK_WIDTH*BALLOON_ZOMBIE_WALK_HEIGHT];

#endif
