#ifndef REAPEATER_SHOOTING_ANIM_H
#define REAPEATER_SHOOTING_ANIM_H

#define REAPEATER_SHOOTING_WIDTH  27
#define REAPEATER_SHOOTING_HEIGHT 30
#define REAPEATER_SHOOTING_FRAMES 2

extern unsigned char reapeater_shooting_frames[REAPEATER_SHOOTING_FRAMES][REAPEATER_SHOOTING_WIDTH*REAPEATER_SHOOTING_HEIGHT];

#endif
