#ifndef POTATO_MINE_POPPING_ANIM_H
#define POTATO_MINE_POPPING_ANIM_H

#define POTATO_MINE_POPPING_WIDTH  28
#define POTATO_MINE_POPPING_HEIGHT 20
#define POTATO_MINE_POPPING_FRAMES 3

extern unsigned char potato_mine_popping_frames[POTATO_MINE_POPPING_FRAMES][POTATO_MINE_POPPING_WIDTH*POTATO_MINE_POPPING_HEIGHT];

#endif
