#ifndef BASIC_ZOMBIE_BURNT_ANIM_H
#define BASIC_ZOMBIE_BURNT_ANIM_H

#define BASIC_ZOMBIE_BURNT_WIDTH  26
#define BASIC_ZOMBIE_BURNT_HEIGHT 43
#define BASIC_ZOMBIE_BURNT_FRAMES 2

extern unsigned char basic_zombie_burnt_frames[BASIC_ZOMBIE_BURNT_FRAMES][BASIC_ZOMBIE_BURNT_WIDTH*BASIC_ZOMBIE_BURNT_HEIGHT];

#endif
