#ifndef BASIC_ZOMBIE_DEATH_ANIM_H
#define BASIC_ZOMBIE_DEATH_ANIM_H

#define BASIC_ZOMBIE_DEATH_WIDTH  44
#define BASIC_ZOMBIE_DEATH_HEIGHT 34
#define BASIC_ZOMBIE_DEATH_FRAMES 9

extern unsigned char basic_zombie_death_frames[BASIC_ZOMBIE_DEATH_FRAMES][BASIC_ZOMBIE_DEATH_WIDTH*BASIC_ZOMBIE_DEATH_HEIGHT];

#endif
