#ifndef BASIC_ZOMBIE_HEAD_ANIM_H
#define BASIC_ZOMBIE_HEAD_ANIM_H

#define BASIC_ZOMBIE_HEAD_WIDTH  32
#define BASIC_ZOMBIE_HEAD_HEIGHT 32
#define BASIC_ZOMBIE_HEAD_FRAMES 1

extern unsigned char basic_zombie_head_frames[BASIC_ZOMBIE_HEAD_FRAMES][BASIC_ZOMBIE_HEAD_WIDTH*BASIC_ZOMBIE_HEAD_HEIGHT];

#endif
