#ifndef BASIC_ZOMBIE_IDLE_ANIM_H
#define BASIC_ZOMBIE_IDLE_ANIM_H

#define BASIC_ZOMBIE_IDLE_WIDTH  35
#define BASIC_ZOMBIE_IDLE_HEIGHT 51
#define BASIC_ZOMBIE_IDLE_FRAMES 5

extern unsigned char basic_zombie_idle_frames[BASIC_ZOMBIE_IDLE_FRAMES][BASIC_ZOMBIE_IDLE_WIDTH*BASIC_ZOMBIE_IDLE_HEIGHT];

#endif
