#ifndef CACTUS_ATTACKING_ANIM_H
#define CACTUS_ATTACKING_ANIM_H

#define CACTUS_ATTACKING_WIDTH  38
#define CACTUS_ATTACKING_HEIGHT 36
#define CACTUS_ATTACKING_FRAMES 2

extern unsigned char cactus_attacking_frames[CACTUS_ATTACKING_FRAMES][CACTUS_ATTACKING_WIDTH*CACTUS_ATTACKING_HEIGHT];

#endif
