#ifndef SNOWPEA_IMPACT_ANIM_H
#define SNOWPEA_IMPACT_ANIM_H

#define SNOWPEA_IMPACT_WIDTH  20
#define SNOWPEA_IMPACT_HEIGHT 32
#define SNOWPEA_IMPACT_FRAMES 3

extern unsigned char snowpea_impact_frames[SNOWPEA_IMPACT_FRAMES][SNOWPEA_IMPACT_WIDTH*SNOWPEA_IMPACT_HEIGHT];

#endif
