#ifndef PEASHOOTER_SHOOTING_ANIM_H
#define PEASHOOTER_SHOOTING_ANIM_H

#define PEASHOOTER_SHOOTING_WIDTH  29
#define PEASHOOTER_SHOOTING_HEIGHT 32
#define PEASHOOTER_SHOOTING_FRAMES 3

extern unsigned char peashooter_shooting_frames[PEASHOOTER_SHOOTING_FRAMES][PEASHOOTER_SHOOTING_WIDTH*PEASHOOTER_SHOOTING_HEIGHT];

#endif
