#ifndef SNOW_PEASHOOTER_ANIM_H
#define SNOW_PEASHOOTER_ANIM_H

#define SNOW_PEASHOOTER_WIDTH  31
#define SNOW_PEASHOOTER_HEIGHT 32
#define SNOW_PEASHOOTER_FRAMES 8

extern unsigned char snow_peashooter_frames[SNOW_PEASHOOTER_FRAMES][SNOW_PEASHOOTER_WIDTH*SNOW_PEASHOOTER_HEIGHT];

#endif
