#ifndef COBCANNON_RISING_ANIM_H
#define COBCANNON_RISING_ANIM_H

#define COBCANNON_RISING_WIDTH  80
#define COBCANNON_RISING_HEIGHT 107
#define COBCANNON_RISING_FRAMES 7

extern unsigned char cobcannon_rising_frames[COBCANNON_RISING_FRAMES][COBCANNON_RISING_WIDTH*COBCANNON_RISING_HEIGHT];

#endif
