#ifndef COBCANNON_USED_ANIM_H
#define COBCANNON_USED_ANIM_H

#define COBCANNON_USED_WIDTH  69
#define COBCANNON_USED_HEIGHT 78
#define COBCANNON_USED_FRAMES 7

extern unsigned char cobcannon_used_frames[COBCANNON_USED_FRAMES][COBCANNON_USED_WIDTH*COBCANNON_USED_HEIGHT];

#endif
