#ifndef COBCANNON_FIRING_ANIM_H
#define COBCANNON_FIRING_ANIM_H

#define COBCANNON_FIRING_WIDTH  72
#define COBCANNON_FIRING_HEIGHT 71
#define COBCANNON_FIRING_FRAMES 11

extern unsigned char cobcannon_firing_frames[COBCANNON_FIRING_FRAMES][COBCANNON_FIRING_WIDTH*COBCANNON_FIRING_HEIGHT];

#endif
