#ifndef COBCANNON_LOADING_ANIM_H
#define COBCANNON_LOADING_ANIM_H

#define COBCANNON_LOADING_WIDTH  73
#define COBCANNON_LOADING_HEIGHT 41
#define COBCANNON_LOADING_FRAMES 7

extern unsigned char cobcannon_loading_frames[COBCANNON_LOADING_FRAMES][COBCANNON_LOADING_WIDTH*COBCANNON_LOADING_HEIGHT];

#endif
