#ifndef WALLNUT_VERY_DAMAGED_ANIM_H
#define WALLNUT_VERY_DAMAGED_ANIM_H

#define WALLNUT_VERY_DAMAGED_WIDTH  28
#define WALLNUT_VERY_DAMAGED_HEIGHT 29
#define WALLNUT_VERY_DAMAGED_FRAMES 5

extern unsigned char wallnut_very_damaged_frames[WALLNUT_VERY_DAMAGED_FRAMES][WALLNUT_VERY_DAMAGED_WIDTH*WALLNUT_VERY_DAMAGED_HEIGHT];

#endif
