#ifndef WALLNUT_DAMAGED_ANIM_H
#define WALLNUT_DAMAGED_ANIM_H

#define WALLNUT_DAMAGED_WIDTH  28
#define WALLNUT_DAMAGED_HEIGHT 32
#define WALLNUT_DAMAGED_FRAMES 5

extern unsigned char wallnut_damaged_frames[WALLNUT_DAMAGED_FRAMES][WALLNUT_DAMAGED_WIDTH*WALLNUT_DAMAGED_HEIGHT];

#endif
