#ifndef CABBAGEPULT_ANIM_H
#define CABBAGEPULT_ANIM_H

#define CABBAGEPULT_WIDTH  30
#define CABBAGEPULT_HEIGHT 28
#define CABBAGEPULT_FRAMES 6

extern unsigned char cabbagepult_frames[CABBAGEPULT_FRAMES][CABBAGEPULT_WIDTH*CABBAGEPULT_HEIGHT];

#endif
