#ifndef CACTUS_GROWING_ANIM_H
#define CACTUS_GROWING_ANIM_H

#define CACTUS_GROWING_WIDTH  39
#define CACTUS_GROWING_HEIGHT 71
#define CACTUS_GROWING_FRAMES 5

extern unsigned char cactus_growing_frames[CACTUS_GROWING_FRAMES][CACTUS_GROWING_WIDTH*CACTUS_GROWING_HEIGHT];

#endif
