#ifndef CHERRYBOMB_EXPLOSION_ANIM_H
#define CHERRYBOMB_EXPLOSION_ANIM_H

#define CHERRYBOMB_EXPLOSION_WIDTH  64
#define CHERRYBOMB_EXPLOSION_HEIGHT 64
#define CHERRYBOMB_EXPLOSION_FRAMES 2

extern unsigned char cherrybomb_explosion_frames[CHERRYBOMB_EXPLOSION_FRAMES][CHERRYBOMB_EXPLOSION_WIDTH*CHERRYBOMB_EXPLOSION_HEIGHT];

#endif
