#ifndef CHERRYBOMB_EXPLOSION_ANIM_H
#define CHERRYBOMB_EXPLOSION_ANIM_H

#define CHERRYBOMB_EXPLOSION_WIDTH  96
#define CHERRYBOMB_EXPLOSION_HEIGHT 68
#define CHERRYBOMB_EXPLOSION_FRAMES 8

extern unsigned char cherrybomb_explosion_frames[CHERRYBOMB_EXPLOSION_FRAMES][CHERRYBOMB_EXPLOSION_WIDTH*CHERRYBOMB_EXPLOSION_HEIGHT];

#endif
