#ifndef COBCANNON_READY_ANIM_H
#define COBCANNON_READY_ANIM_H

#define COBCANNON_READY_WIDTH  73
#define COBCANNON_READY_HEIGHT 41
#define COBCANNON_READY_FRAMES 6

extern unsigned char cobcannon_ready_frames[COBCANNON_READY_FRAMES][COBCANNON_READY_WIDTH*COBCANNON_READY_HEIGHT];

#endif
