#ifndef JALAPENO_ATTACKING_ANIM_H
#define JALAPENO_ATTACKING_ANIM_H

#define JALAPENO_ATTACKING_WIDTH  22
#define JALAPENO_ATTACKING_HEIGHT 34
#define JALAPENO_ATTACKING_FRAMES 3

extern unsigned char jalapeno_attacking_frames[JALAPENO_ATTACKING_FRAMES][JALAPENO_ATTACKING_WIDTH*JALAPENO_ATTACKING_HEIGHT];

#endif
