#ifndef MARIGOLD_ANIM_H
#define MARIGOLD_ANIM_H

#define MARIGOLD_WIDTH  26
#define MARIGOLD_HEIGHT 32
#define MARIGOLD_FRAMES 9

extern unsigned char marigold_frames[MARIGOLD_FRAMES][MARIGOLD_WIDTH*MARIGOLD_HEIGHT];

#endif
