#ifndef MARIGOLD_ATTACKING_ANIM_H
#define MARIGOLD_ATTACKING_ANIM_H

#define MARIGOLD_ATTACKING_WIDTH  26
#define MARIGOLD_ATTACKING_HEIGHT 31
#define MARIGOLD_ATTACKING_FRAMES 4

extern unsigned char marigold_attacking_frames[MARIGOLD_ATTACKING_FRAMES][MARIGOLD_ATTACKING_WIDTH*MARIGOLD_ATTACKING_HEIGHT];

#endif
