#ifndef SUNFLOWER_PRODUCING_ANIM_H
#define SUNFLOWER_PRODUCING_ANIM_H

#define SUNFLOWER_PRODUCING_WIDTH  28
#define SUNFLOWER_PRODUCING_HEIGHT 31
#define SUNFLOWER_PRODUCING_FRAMES 6

extern unsigned char sunflower_producing_frames[SUNFLOWER_PRODUCING_FRAMES][SUNFLOWER_PRODUCING_WIDTH*SUNFLOWER_PRODUCING_HEIGHT];

#endif
