#ifndef TWINSUNFLOWER_ANIM_H
#define TWINSUNFLOWER_ANIM_H

#define TWINSUNFLOWER_WIDTH  50
#define TWINSUNFLOWER_HEIGHT 41
#define TWINSUNFLOWER_FRAMES 10

extern unsigned char twinsunflower_frames[TWINSUNFLOWER_FRAMES][TWINSUNFLOWER_WIDTH*TWINSUNFLOWER_HEIGHT];

#endif
