#ifndef KERNELPULT_ANIM_H
#define KERNELPULT_ANIM_H

#define KERNELPULT_WIDTH  44
#define KERNELPULT_HEIGHT 36
#define KERNELPULT_FRAMES 4

extern unsigned char kernelpult_frames[KERNELPULT_FRAMES][KERNELPULT_WIDTH*KERNELPULT_HEIGHT];

#endif
