#ifndef KERNELPULT_ATTACKING_ANIM_H
#define KERNELPULT_ATTACKING_ANIM_H

#define KERNELPULT_ATTACKING_WIDTH  45
#define KERNELPULT_ATTACKING_HEIGHT 61
#define KERNELPULT_ATTACKING_FRAMES 7

extern unsigned char kernelpult_attacking_frames[KERNELPULT_ATTACKING_FRAMES][KERNELPULT_ATTACKING_WIDTH*KERNELPULT_ATTACKING_HEIGHT];

#endif
