#ifndef WINTERMELON_ANIM_H
#define WINTERMELON_ANIM_H

#define WINTERMELON_WIDTH  51
#define WINTERMELON_HEIGHT 42
#define WINTERMELON_FRAMES 6

extern unsigned char wintermelon_frames[WINTERMELON_FRAMES][WINTERMELON_WIDTH*WINTERMELON_HEIGHT];

#endif
