#ifndef JALAPENO_FIRE_ANIM_H
#define JALAPENO_FIRE_ANIM_H

#define JALAPENO_FIRE_WIDTH  22
#define JALAPENO_FIRE_HEIGHT 14
#define JALAPENO_FIRE_FRAMES 2

extern unsigned char jalapeno_fire_frames[JALAPENO_FIRE_FRAMES][JALAPENO_FIRE_WIDTH*JALAPENO_FIRE_HEIGHT];

#endif
