#ifndef POGO_ZOMBIE_HEAD_ANIM_H
#define POGO_ZOMBIE_HEAD_ANIM_H

#define POGO_ZOMBIE_HEAD_WIDTH  19
#define POGO_ZOMBIE_HEAD_HEIGHT 24
#define POGO_ZOMBIE_HEAD_FRAMES 1

extern unsigned char pogo_zombie_head_frames[POGO_ZOMBIE_HEAD_FRAMES][POGO_ZOMBIE_HEAD_WIDTH*POGO_ZOMBIE_HEAD_HEIGHT];

#endif
