#ifndef POGO_ZOMBIE_DEATH_ANIM_H
#define POGO_ZOMBIE_DEATH_ANIM_H

#define POGO_ZOMBIE_DEATH_WIDTH  34
#define POGO_ZOMBIE_DEATH_HEIGHT 32
#define POGO_ZOMBIE_DEATH_FRAMES 9

extern unsigned char pogo_zombie_death_frames[POGO_ZOMBIE_DEATH_FRAMES][POGO_ZOMBIE_DEATH_WIDTH*POGO_ZOMBIE_DEATH_HEIGHT];

#endif
