#ifndef CONE_ZOMBIE_CONE_ANIM_H
#define CONE_ZOMBIE_CONE_ANIM_H

#define CONE_ZOMBIE_CONE_WIDTH  21
#define CONE_ZOMBIE_CONE_HEIGHT 20
#define CONE_ZOMBIE_CONE_FRAMES 3

extern unsigned char cone_zombie_cone_frames[CONE_ZOMBIE_CONE_FRAMES][CONE_ZOMBIE_CONE_WIDTH*CONE_ZOMBIE_CONE_HEIGHT];

#endif
