#ifndef CONE_ZOMBIE_IDLE_ANIM_H
#define CONE_ZOMBIE_IDLE_ANIM_H

#define CONE_ZOMBIE_IDLE_WIDTH  35
#define CONE_ZOMBIE_IDLE_HEIGHT 57
#define CONE_ZOMBIE_IDLE_FRAMES 5

extern unsigned char cone_zombie_idle_frames[CONE_ZOMBIE_IDLE_FRAMES][CONE_ZOMBIE_IDLE_WIDTH*CONE_ZOMBIE_IDLE_HEIGHT];

#endif
