#ifndef BASEBALL_ZOMBIE_ARM_ANIM_H
#define BASEBALL_ZOMBIE_ARM_ANIM_H

#define BASEBALL_ZOMBIE_ARM_WIDTH  16
#define BASEBALL_ZOMBIE_ARM_HEIGHT 16
#define BASEBALL_ZOMBIE_ARM_FRAMES 1

extern unsigned char baseball_zombie_arm_frames[BASEBALL_ZOMBIE_ARM_FRAMES][BASEBALL_ZOMBIE_ARM_WIDTH*BASEBALL_ZOMBIE_ARM_HEIGHT];

#endif
