#ifndef BASEBALL_ZOMBIE_HEAD_ANIM_H
#define BASEBALL_ZOMBIE_HEAD_ANIM_H

#define BASEBALL_ZOMBIE_HEAD_WIDTH  32
#define BASEBALL_ZOMBIE_HEAD_HEIGHT 32
#define BASEBALL_ZOMBIE_HEAD_FRAMES 1

extern unsigned char baseball_zombie_head_frames[BASEBALL_ZOMBIE_HEAD_FRAMES][BASEBALL_ZOMBIE_HEAD_WIDTH*BASEBALL_ZOMBIE_HEAD_HEIGHT];

#endif
