#ifndef BASEBALL_ZOMBIE_BALL_ANIM_H
#define BASEBALL_ZOMBIE_BALL_ANIM_H

#define BASEBALL_ZOMBIE_BALL_WIDTH  16
#define BASEBALL_ZOMBIE_BALL_HEIGHT 16
#define BASEBALL_ZOMBIE_BALL_FRAMES 1

extern unsigned char baseball_zombie_ball_frames[BASEBALL_ZOMBIE_BALL_FRAMES][BASEBALL_ZOMBIE_BALL_WIDTH*BASEBALL_ZOMBIE_BALL_HEIGHT];

#endif
