#ifndef BASEBALL_ZOMBIE_IDLE_ANIM_H
#define BASEBALL_ZOMBIE_IDLE_ANIM_H

#define BASEBALL_ZOMBIE_IDLE_WIDTH  37
#define BASEBALL_ZOMBIE_IDLE_HEIGHT 51
#define BASEBALL_ZOMBIE_IDLE_FRAMES 5

extern unsigned char baseball_zombie_idle_frames[BASEBALL_ZOMBIE_IDLE_FRAMES][BASEBALL_ZOMBIE_IDLE_WIDTH*BASEBALL_ZOMBIE_IDLE_HEIGHT];

#endif
