#ifndef BASEBALL_ZOMBIE_CAP_ANIM_H
#define BASEBALL_ZOMBIE_CAP_ANIM_H

#define BASEBALL_ZOMBIE_CAP_WIDTH  32
#define BASEBALL_ZOMBIE_CAP_HEIGHT 16
#define BASEBALL_ZOMBIE_CAP_FRAMES 1

extern unsigned char baseball_zombie_cap_frames[BASEBALL_ZOMBIE_CAP_FRAMES][BASEBALL_ZOMBIE_CAP_WIDTH*BASEBALL_ZOMBIE_CAP_HEIGHT];

#endif
