#ifndef YETI_ZOMBIE_HEAD_ANIM_H
#define YETI_ZOMBIE_HEAD_ANIM_H

#define YETI_ZOMBIE_HEAD_WIDTH  28
#define YETI_ZOMBIE_HEAD_HEIGHT 29
#define YETI_ZOMBIE_HEAD_FRAMES 1

extern unsigned char yeti_zombie_head_frames[YETI_ZOMBIE_HEAD_FRAMES][YETI_ZOMBIE_HEAD_WIDTH*YETI_ZOMBIE_HEAD_HEIGHT];

#endif
