#ifndef YETI_ZOMBIE_IDLE_ANIM_H
#define YETI_ZOMBIE_IDLE_ANIM_H

#define YETI_ZOMBIE_IDLE_WIDTH  41
#define YETI_ZOMBIE_IDLE_HEIGHT 65
#define YETI_ZOMBIE_IDLE_FRAMES 9

extern unsigned char yeti_zombie_idle_frames[YETI_ZOMBIE_IDLE_FRAMES][YETI_ZOMBIE_IDLE_WIDTH*YETI_ZOMBIE_IDLE_HEIGHT];

#endif
