#ifndef YETI_ZOMBIE_ARM_ANIM_H
#define YETI_ZOMBIE_ARM_ANIM_H

#define YETI_ZOMBIE_ARM_WIDTH  12
#define YETI_ZOMBIE_ARM_HEIGHT 23
#define YETI_ZOMBIE_ARM_FRAMES 1

extern unsigned char yeti_zombie_arm_frames[YETI_ZOMBIE_ARM_FRAMES][YETI_ZOMBIE_ARM_WIDTH*YETI_ZOMBIE_ARM_HEIGHT];

#endif
