#ifndef YETI_ZOMBIE_BURNT_ANIM_H
#define YETI_ZOMBIE_BURNT_ANIM_H

#define YETI_ZOMBIE_BURNT_WIDTH  41
#define YETI_ZOMBIE_BURNT_HEIGHT 65
#define YETI_ZOMBIE_BURNT_FRAMES 1

extern unsigned char yeti_zombie_burnt_frames[YETI_ZOMBIE_BURNT_FRAMES][YETI_ZOMBIE_BURNT_WIDTH*YETI_ZOMBIE_BURNT_HEIGHT];

#endif
