#ifndef CHOMPER_ATTACKING_ANIM_H
#define CHOMPER_ATTACKING_ANIM_H

#define CHOMPER_ATTACKING_WIDTH  50
#define CHOMPER_ATTACKING_HEIGHT 52
#define CHOMPER_ATTACKING_FRAMES 6

extern unsigned char chomper_attacking_frames[CHOMPER_ATTACKING_FRAMES][CHOMPER_ATTACKING_WIDTH*CHOMPER_ATTACKING_HEIGHT];

#endif
