#ifndef CHOMPER_CHEWING_ANIM_H
#define CHOMPER_CHEWING_ANIM_H

#define CHOMPER_CHEWING_WIDTH  37
#define CHOMPER_CHEWING_HEIGHT 38
#define CHOMPER_CHEWING_FRAMES 3

extern unsigned char chomper_chewing_frames[CHOMPER_CHEWING_FRAMES][CHOMPER_CHEWING_WIDTH*CHOMPER_CHEWING_HEIGHT];

#endif
