#ifndef PEABULLET_IMPACT_ANIM_H
#define PEABULLET_IMPACT_ANIM_H

#define PEABULLET_IMPACT_WIDTH  15
#define PEABULLET_IMPACT_HEIGHT 32
#define PEABULLET_IMPACT_FRAMES 2

extern unsigned char peabullet_impact_frames[PEABULLET_IMPACT_FRAMES][PEABULLET_IMPACT_WIDTH*PEABULLET_IMPACT_HEIGHT];

#endif
