#ifndef WINTERMELON_IMPACT_ANIM_H
#define WINTERMELON_IMPACT_ANIM_H

#define WINTERMELON_IMPACT_WIDTH  64
#define WINTERMELON_IMPACT_HEIGHT 48
#define WINTERMELON_IMPACT_FRAMES 6

extern unsigned char wintermelon_impact_frames[WINTERMELON_IMPACT_FRAMES][WINTERMELON_IMPACT_WIDTH*WINTERMELON_IMPACT_HEIGHT];

#endif
