#ifndef DIGGER_ZOMBIE_ARM_ANIM_H
#define DIGGER_ZOMBIE_ARM_ANIM_H

#define DIGGER_ZOMBIE_ARM_WIDTH  8
#define DIGGER_ZOMBIE_ARM_HEIGHT 14
#define DIGGER_ZOMBIE_ARM_FRAMES 1

extern unsigned char digger_zombie_arm_frames[DIGGER_ZOMBIE_ARM_FRAMES][DIGGER_ZOMBIE_ARM_WIDTH*DIGGER_ZOMBIE_ARM_HEIGHT];

#endif
