#ifndef DIGGER_ZOMBIE_HEAD_ANIM_H
#define DIGGER_ZOMBIE_HEAD_ANIM_H

#define DIGGER_ZOMBIE_HEAD_WIDTH  22
#define DIGGER_ZOMBIE_HEAD_HEIGHT 20
#define DIGGER_ZOMBIE_HEAD_FRAMES 1

extern unsigned char digger_zombie_head_frames[DIGGER_ZOMBIE_HEAD_FRAMES][DIGGER_ZOMBIE_HEAD_WIDTH*DIGGER_ZOMBIE_HEAD_HEIGHT];

#endif
