#ifndef GARLIC_DAMAGED_ANIM_H
#define GARLIC_DAMAGED_ANIM_H

#define GARLIC_DAMAGED_WIDTH  23
#define GARLIC_DAMAGED_HEIGHT 42
#define GARLIC_DAMAGED_FRAMES 6

extern unsigned char garlic_damaged_frames[GARLIC_DAMAGED_FRAMES][GARLIC_DAMAGED_WIDTH*GARLIC_DAMAGED_HEIGHT];

#endif
