#ifndef GARLIC_VERY_DAMAGED_ANIM_H
#define GARLIC_VERY_DAMAGED_ANIM_H

#define GARLIC_VERY_DAMAGED_WIDTH  23
#define GARLIC_VERY_DAMAGED_HEIGHT 42
#define GARLIC_VERY_DAMAGED_FRAMES 6

extern unsigned char garlic_very_damaged_frames[GARLIC_VERY_DAMAGED_FRAMES][GARLIC_VERY_DAMAGED_WIDTH*GARLIC_VERY_DAMAGED_HEIGHT];

#endif
