#ifndef FOOTBALL_ZOMBIE_WALK_ANIM_H
#define FOOTBALL_ZOMBIE_WALK_ANIM_H

#define FOOTBALL_ZOMBIE_WALK_WIDTH  49
#define FOOTBALL_ZOMBIE_WALK_HEIGHT 52
#define FOOTBALL_ZOMBIE_WALK_FRAMES 8

extern unsigned char football_zombie_walk_frames[FOOTBALL_ZOMBIE_WALK_FRAMES][FOOTBALL_ZOMBIE_WALK_WIDTH*FOOTBALL_ZOMBIE_WALK_HEIGHT];

#endif
