#ifndef FOOTBALL_ZOMBIE_HEAD_ANIM_H
#define FOOTBALL_ZOMBIE_HEAD_ANIM_H

#define FOOTBALL_ZOMBIE_HEAD_WIDTH  21
#define FOOTBALL_ZOMBIE_HEAD_HEIGHT 21
#define FOOTBALL_ZOMBIE_HEAD_FRAMES 1

extern unsigned char football_zombie_head_frames[FOOTBALL_ZOMBIE_HEAD_FRAMES][FOOTBALL_ZOMBIE_HEAD_WIDTH*FOOTBALL_ZOMBIE_HEAD_HEIGHT];

#endif
