#ifndef FOOTBALL_ZOMBIE_IDLE_ANIM_H
#define FOOTBALL_ZOMBIE_IDLE_ANIM_H

#define FOOTBALL_ZOMBIE_IDLE_WIDTH  43
#define FOOTBALL_ZOMBIE_IDLE_HEIGHT 53
#define FOOTBALL_ZOMBIE_IDLE_FRAMES 4

extern unsigned char football_zombie_idle_frames[FOOTBALL_ZOMBIE_IDLE_FRAMES][FOOTBALL_ZOMBIE_IDLE_WIDTH*FOOTBALL_ZOMBIE_IDLE_HEIGHT];

#endif
