#ifndef MELONPULT_ATTACKING_ANIM_H
#define MELONPULT_ATTACKING_ANIM_H

#define MELONPULT_ATTACKING_WIDTH  55
#define MELONPULT_ATTACKING_HEIGHT 63
#define MELONPULT_ATTACKING_FRAMES 6

extern unsigned char melonpult_attacking_frames[MELONPULT_ATTACKING_FRAMES][MELONPULT_ATTACKING_WIDTH*MELONPULT_ATTACKING_HEIGHT];

#endif
