#ifndef CATAPULT_ZOMBIE_BALL_ANIM_H
#define CATAPULT_ZOMBIE_BALL_ANIM_H

#define CATAPULT_ZOMBIE_BALL_WIDTH  16
#define CATAPULT_ZOMBIE_BALL_HEIGHT 16
#define CATAPULT_ZOMBIE_BALL_FRAMES 1

extern unsigned char catapult_zombie_ball_frames[CATAPULT_ZOMBIE_BALL_FRAMES][CATAPULT_ZOMBIE_BALL_WIDTH*CATAPULT_ZOMBIE_BALL_HEIGHT];

#endif
