#ifndef CATAPULT_ZOMBIE_WALK_ANIM_H
#define CATAPULT_ZOMBIE_WALK_ANIM_H

#define CATAPULT_ZOMBIE_WALK_WIDTH  63
#define CATAPULT_ZOMBIE_WALK_HEIGHT 55
#define CATAPULT_ZOMBIE_WALK_FRAMES 6

extern unsigned char catapult_zombie_walk_frames[CATAPULT_ZOMBIE_WALK_FRAMES][CATAPULT_ZOMBIE_WALK_WIDTH*CATAPULT_ZOMBIE_WALK_HEIGHT];

#endif
