#ifndef BUTTER_IMPACT_ANIM_H
#define BUTTER_IMPACT_ANIM_H

#define BUTTER_IMPACT_WIDTH  16
#define BUTTER_IMPACT_HEIGHT 17
#define BUTTER_IMPACT_FRAMES 2

extern unsigned char butter_impact_frames[BUTTER_IMPACT_FRAMES][BUTTER_IMPACT_WIDTH*BUTTER_IMPACT_HEIGHT];

#endif
