#ifndef COBCANNON_IMPACT_ANIM_H
#define COBCANNON_IMPACT_ANIM_H

#define COBCANNON_IMPACT_WIDTH  96
#define COBCANNON_IMPACT_HEIGHT 64
#define COBCANNON_IMPACT_FRAMES 7

extern unsigned char cobcannon_impact_frames[COBCANNON_IMPACT_FRAMES][COBCANNON_IMPACT_WIDTH*COBCANNON_IMPACT_HEIGHT];

#endif
