#ifndef CONE_ZOMBIE_WALK_ANIM_H
#define CONE_ZOMBIE_WALK_ANIM_H

#define CONE_ZOMBIE_WALK_WIDTH  35
#define CONE_ZOMBIE_WALK_HEIGHT 55
#define CONE_ZOMBIE_WALK_FRAMES 7

extern unsigned char cone_zombie_walk_frames[CONE_ZOMBIE_WALK_FRAMES][CONE_ZOMBIE_WALK_WIDTH*CONE_ZOMBIE_WALK_HEIGHT];

#endif
