#ifndef CONE_ZOMBIE_FIGHT_ANIM_H
#define CONE_ZOMBIE_FIGHT_ANIM_H

#define CONE_ZOMBIE_FIGHT_WIDTH  36
#define CONE_ZOMBIE_FIGHT_HEIGHT 55
#define CONE_ZOMBIE_FIGHT_FRAMES 7

extern unsigned char cone_zombie_fight_frames[CONE_ZOMBIE_FIGHT_FRAMES][CONE_ZOMBIE_FIGHT_WIDTH*CONE_ZOMBIE_FIGHT_HEIGHT];

#endif
