#ifndef DISCO_ZOMBIE_WALK_ANIM_H
#define DISCO_ZOMBIE_WALK_ANIM_H

#define DISCO_ZOMBIE_WALK_WIDTH  30
#define DISCO_ZOMBIE_WALK_HEIGHT 47
#define DISCO_ZOMBIE_WALK_FRAMES 10

extern unsigned char disco_zombie_walk_frames[DISCO_ZOMBIE_WALK_FRAMES][DISCO_ZOMBIE_WALK_WIDTH*DISCO_ZOMBIE_WALK_HEIGHT];

#endif
