#ifndef DISCO_ZOMBIE_FIGHT_ANIM_H
#define DISCO_ZOMBIE_FIGHT_ANIM_H

#define DISCO_ZOMBIE_FIGHT_WIDTH  31
#define DISCO_ZOMBIE_FIGHT_HEIGHT 47
#define DISCO_ZOMBIE_FIGHT_FRAMES 6

extern unsigned char disco_zombie_fight_frames[DISCO_ZOMBIE_FIGHT_FRAMES][DISCO_ZOMBIE_FIGHT_WIDTH*DISCO_ZOMBIE_FIGHT_HEIGHT];

#endif
