#ifndef POGO_ZOMBIE_POGO_ANIM_H
#define POGO_ZOMBIE_POGO_ANIM_H

#define POGO_ZOMBIE_POGO_WIDTH  30
#define POGO_ZOMBIE_POGO_HEIGHT 47
#define POGO_ZOMBIE_POGO_FRAMES 5

extern unsigned char pogo_zombie_pogo_frames[POGO_ZOMBIE_POGO_FRAMES][POGO_ZOMBIE_POGO_WIDTH*POGO_ZOMBIE_POGO_HEIGHT];

#endif
