#ifndef POGO_ZOMBIE_WALK_ANIM_H
#define POGO_ZOMBIE_WALK_ANIM_H

#define POGO_ZOMBIE_WALK_WIDTH  30
#define POGO_ZOMBIE_WALK_HEIGHT 47
#define POGO_ZOMBIE_WALK_FRAMES 5

extern unsigned char pogo_zombie_walk_frames[POGO_ZOMBIE_WALK_FRAMES][POGO_ZOMBIE_WALK_WIDTH*POGO_ZOMBIE_WALK_HEIGHT];

#endif
