#ifndef POGO_ZOMBIE_FIGHT_ANIM_H
#define POGO_ZOMBIE_FIGHT_ANIM_H

#define POGO_ZOMBIE_FIGHT_WIDTH  31
#define POGO_ZOMBIE_FIGHT_HEIGHT 47
#define POGO_ZOMBIE_FIGHT_FRAMES 7

extern unsigned char pogo_zombie_fight_frames[POGO_ZOMBIE_FIGHT_FRAMES][POGO_ZOMBIE_FIGHT_WIDTH*POGO_ZOMBIE_FIGHT_HEIGHT];

#endif
