#ifndef DISCO_ZOMBIE_DANCE_ANIM_H
#define DISCO_ZOMBIE_DANCE_ANIM_H

#define DISCO_ZOMBIE_DANCE_WIDTH  49
#define DISCO_ZOMBIE_DANCE_HEIGHT 75
#define DISCO_ZOMBIE_DANCE_FRAMES 6

extern unsigned char disco_zombie_dance_frames[DISCO_ZOMBIE_DANCE_FRAMES][DISCO_ZOMBIE_DANCE_WIDTH*DISCO_ZOMBIE_DANCE_HEIGHT];

#endif
