#ifndef DISCO_ZOMBIE_FIGHT_ANIM_H
#define DISCO_ZOMBIE_FIGHT_ANIM_H

#define DISCO_ZOMBIE_FIGHT_WIDTH  45
#define DISCO_ZOMBIE_FIGHT_HEIGHT 73
#define DISCO_ZOMBIE_FIGHT_FRAMES 10

extern unsigned char disco_zombie_fight_frames[DISCO_ZOMBIE_FIGHT_FRAMES][DISCO_ZOMBIE_FIGHT_WIDTH*DISCO_ZOMBIE_FIGHT_HEIGHT];

#endif
