#ifndef DISCO_ZOMBIE_WALK_ANIM_H
#define DISCO_ZOMBIE_WALK_ANIM_H

#define DISCO_ZOMBIE_WALK_WIDTH  45
#define DISCO_ZOMBIE_WALK_HEIGHT 73
#define DISCO_ZOMBIE_WALK_FRAMES 4

extern unsigned char disco_zombie_walk_frames[DISCO_ZOMBIE_WALK_FRAMES][DISCO_ZOMBIE_WALK_WIDTH*DISCO_ZOMBIE_WALK_HEIGHT];

#endif
