#ifndef DISCO_ZOMBIE_DEATH_ANIM_H
#define DISCO_ZOMBIE_DEATH_ANIM_H

#define DISCO_ZOMBIE_DEATH_WIDTH  69
#define DISCO_ZOMBIE_DEATH_HEIGHT 53
#define DISCO_ZOMBIE_DEATH_FRAMES 14

extern unsigned char disco_zombie_death_frames[DISCO_ZOMBIE_DEATH_FRAMES][DISCO_ZOMBIE_DEATH_WIDTH*DISCO_ZOMBIE_DEATH_HEIGHT];

#endif
