#ifndef TORCHWOOD_FIRE_ANIM_H
#define TORCHWOOD_FIRE_ANIM_H

#define TORCHWOOD_FIRE_WIDTH  18
#define TORCHWOOD_FIRE_HEIGHT 14
#define TORCHWOOD_FIRE_FRAMES 4

extern unsigned char torchwood_fire_frames[TORCHWOOD_FIRE_FRAMES][TORCHWOOD_FIRE_WIDTH*TORCHWOOD_FIRE_HEIGHT];

#endif
