#ifndef THREEPEATER_SHOOTING_ANIM_H
#define THREEPEATER_SHOOTING_ANIM_H

#define THREEPEATER_SHOOTING_WIDTH  38
#define THREEPEATER_SHOOTING_HEIGHT 37
#define THREEPEATER_SHOOTING_FRAMES 2

extern unsigned char threepeater_shooting_frames[THREEPEATER_SHOOTING_FRAMES][THREEPEATER_SHOOTING_WIDTH*THREEPEATER_SHOOTING_HEIGHT];

#endif
