#ifndef THREEPEATER_ANIM_H
#define THREEPEATER_ANIM_H

#define THREEPEATER_WIDTH  38
#define THREEPEATER_HEIGHT 37
#define THREEPEATER_FRAMES 8

extern unsigned char threepeater_frames[THREEPEATER_FRAMES][THREEPEATER_WIDTH*THREEPEATER_HEIGHT];

#endif
