#ifndef CHERRYBOMB_ATTACKING_ANIM_H
#define CHERRYBOMB_ATTACKING_ANIM_H

#define CHERRYBOMB_ATTACKING_WIDTH  52
#define CHERRYBOMB_ATTACKING_HEIGHT 38
#define CHERRYBOMB_ATTACKING_FRAMES 4

extern unsigned char cherrybomb_attacking_frames[CHERRYBOMB_ATTACKING_FRAMES][CHERRYBOMB_ATTACKING_WIDTH*CHERRYBOMB_ATTACKING_HEIGHT];

#endif
