#ifndef BLOVER_ATTACKING_ANIM_H
#define BLOVER_ATTACKING_ANIM_H

#define BLOVER_ATTACKING_WIDTH  54
#define BLOVER_ATTACKING_HEIGHT 53
#define BLOVER_ATTACKING_FRAMES 4

extern unsigned char blover_attacking_frames[BLOVER_ATTACKING_FRAMES][BLOVER_ATTACKING_WIDTH*BLOVER_ATTACKING_HEIGHT];

#endif
