#ifndef PLANT_TYPE_H
#define PLANT_TYPE_H

enum PlantType {
    PLANT_PEASHOOTER,
    PLANT_SNOW_PEASHOOTER,
    PLANT_SUNFLOWER,
    PLANT_JALAPENO,
    PLANT_POTATO_MINE,
    PLANT_WALLNUT,
    PLANT_CHOMPER,
    PLANT_GATLING_PEA,
    PLANT_BLOVER,
    PLANT_CABBAGEPULT,
    PLANT_CACTUS,
    PLANT_CHERRYBOMB,
    PLANT_COBCANNON,
    PLANT_GARLIC,
    PLANT_KERNELPULT,
    PLANT_MARIGOLD,
    PLANT_MELONPULT
};

#endif
