#ifndef GATLINGPEA_SHOOTING_ANIM_H
#define GATLINGPEA_SHOOTING_ANIM_H

#define GATLINGPEA_SHOOTING_WIDTH  38
#define GATLINGPEA_SHOOTING_HEIGHT 34
#define GATLINGPEA_SHOOTING_FRAMES 8

extern unsigned char gatlingpea_shooting_frames[GATLINGPEA_SHOOTING_FRAMES][GATLINGPEA_SHOOTING_WIDTH*GATLINGPEA_SHOOTING_HEIGHT];

#endif
