#ifndef GATLINGPEA_IDLE_ANIM_H
#define GATLINGPEA_IDLE_ANIM_H

#define GATLINGPEA_IDLE_WIDTH  32
#define GATLINGPEA_IDLE_HEIGHT 35
#define GATLINGPEA_IDLE_FRAMES 8

extern unsigned char gatlingpea_idle_frames[GATLINGPEA_IDLE_FRAMES][GATLINGPEA_IDLE_WIDTH*GATLINGPEA_IDLE_HEIGHT];

#endif
