#ifndef JALAPENO_ZOMBIE_WALK_ANIM_H
#define JALAPENO_ZOMBIE_WALK_ANIM_H

#define JALAPENO_ZOMBIE_WALK_WIDTH  29
#define JALAPENO_ZOMBIE_WALK_HEIGHT 49
#define JALAPENO_ZOMBIE_WALK_FRAMES 7

extern unsigned char jalapeno_zombie_walk_frames[JALAPENO_ZOMBIE_WALK_FRAMES][JALAPENO_ZOMBIE_WALK_WIDTH*JALAPENO_ZOMBIE_WALK_HEIGHT];

#endif
