#ifndef JALAPENO_ZOMBIE_IDLE_ANIM_H
#define JALAPENO_ZOMBIE_IDLE_ANIM_H

#define JALAPENO_ZOMBIE_IDLE_WIDTH  29
#define JALAPENO_ZOMBIE_IDLE_HEIGHT 43
#define JALAPENO_ZOMBIE_IDLE_FRAMES 5

extern unsigned char jalapeno_zombie_idle_frames[JALAPENO_ZOMBIE_IDLE_FRAMES][JALAPENO_ZOMBIE_IDLE_WIDTH*JALAPENO_ZOMBIE_IDLE_HEIGHT];

#endif
